version: 2.1
orbs:
  python: circleci/python@2
jobs:
  build:
    working_directory: ~/rsvpbot

    docker:
      - image: cimg/python:3.11.1
        environment:
          PYTHONUNBUFFERED: true
          RC_ROOT: http://localhost:5000/ # overridden by tests.py
          RSVPBOT_PRODUCTION: true
          ZULIP_RSVP_EMAIL: fake-email@recurse.zulipchat.com
          ZULIP_RSVP_KEY: fake-key
          RC_CLIENT_ID: fake-client-id
          RC_CLIENT_SECRET: fake-client-secret
          DATABASE_URL: postgresql://localhost/rsvpbot_test

      - image: cimg/postgres:14.6
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: rsvpbot_test

    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - python/install-packages:
          pkg-manager: pip
      
      - run:
          name: Run migrations
          command: alembic upgrade head

      - run:
          name: Tests
          command: python tests.py
