"""Add created_at to event

Revision ID: 4f995bad30bd
Revises: e90bfe0c2a18
Create Date: 2017-05-15 16:18:27.131195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f995bad30bd'
down_revision = 'e90bfe0c2a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'created_at')
    # ### end Alembic commands ###
