"""remove token

Revision ID: 5f6cb6217ac5
Revises: 4f995bad30bd
Create Date: 2017-05-16 11:33:06.457310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6cb6217ac5'
down_revision = '4f995bad30bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_token_key', 'event', type_='unique')
    op.drop_column('event', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('event_token_key', 'event', ['token'])
    # ### end Alembic commands ###
