"""add timezone to events

Revision ID: 94c575f6e10f
Revises: 753e7343bbf9
Create Date: 2017-05-18 16:10:19.589104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c575f6e10f'
down_revision = '753e7343bbf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'timezone')
    # ### end Alembic commands ###
