"""Add created_by, end_time, start_time, and url to events

Revision ID: d4d0517e8385
Revises: 5f6cb6217ac5
Create Date: 2017-05-16 11:35:58.884254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d0517e8385'
down_revision = '5f6cb6217ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('event', sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('event', sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('event', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'url')
    op.drop_column('event', 'start_time')
    op.drop_column('event', 'end_time')
    op.drop_column('event', 'created_by')
    # ### end Alembic commands ###
